os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_REFERENCE="Eigen3/3.2.9"
    - CONAN_USERNAME="bilke"
    - CONAN_CHANNEL="stable"

  matrix:
    - CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49
install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
